---
- name: 'Check if Windows Exporter is installed'
  ansible.windows.win_stat:
    path: 'C:\Program Files\windows_exporter\windows_exporter.exe'
  register: _windows_exporter_is_installed

- name: 'Check current Windows Exporter version'
  ansible.windows.win_command: '"C:\Program Files\windows_exporter\windows_exporter.exe" --version'
  failed_when: false
  changed_when: false
  register: _windows_exporter_version_check

- name: 'Download and unarchive Windows Exporter'
  when:
    - not _windows_exporter_is_installed.stat.exists or
      ( _windows_exporter_version_check.stderr_lines | length > 0 and
      windows_exporter_version not in _windows_exporter_version_check.stderr_lines[0].split(" ")[2] ) or
      ( _windows_exporter_version_check.stdout_lines | length > 0 and
      windows_exporter_version not in _windows_exporter_version_check.stdout_lines[0].split(" ")[2] )
  block:
    - name: 'Download Windows Exporter into temporary location'
      ansible.windows.win_get_url:
        url: '{{ windows_exporter_download_url }}/{{ windows_exporter_package_name }}'
        dest: '{{ windows_exporter_download_path }}'
      check_mode: false
      when: not windows_exporter_skip_download
    
    - name: 'Ensure windows_exporter package is present'
      ansible.windows.win_stat:
        path: '{{ windows_exporter_download_path }}'
      register: stat_exporter_package
      failed_when: not stat_exporter_package.stat.exists
          
    - name: 'Install Windows Exporter'
      ansible.windows.win_package:
        path: '{{ windows_exporter_download_path }}'
        state: present
      when: not ansible_check_mode
